name: blank_slots
arch: amd64
platform: linux
version: 0.0.1
section: default
priority: extra
maintainer: "Soufiane Ar-Razouki <soufiane.arrazouki@clearchannel.be>"
description: "blank slot detection package"
vendor: "Tech Europe"
license: "MIT"
homepage: "https://github.com/clearchannelinternational/blank_slots"

contents:
  - src: /tmp/blank_slots/bin
    dst: /usr/bin
# overrides:
#   deb:
#     fields:
#       Depends: "python3, ffmpeg, python3-pil"