name: blankwatch

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  package:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-numpy python3-xlib x11-utils procps

      - name: Copy Files to the corresponding destinations
        run: |
          sudo cp ./opt/scripts/blank_slots/blank_slot.py /opt/scripts/blankwatch.py
          sudo cp ./etc/systemd/blank_slot.service /etc/systemd/system/blankwatch.service

      - name: Create and set persmissions for required files
        run: |
          sudo touch /var/log/blankwatch.log
          sudo chmod 755 /var/log/blankwatch.log

      - name: Start the service
        run: |
          sudo systemctl enable blankwatch.service
          sudo systemctl start blankwatch.service

  call-release:
    uses: ./.github/workflows/release.yml
    with:
      tags: ${{ github.ref_name }}
