name: Build and Package with nfpm

on:
  workflow_call:
    inputs:
      tags:
        type: string
        description: "Tag name"
        default: "v*"

jobs:
  package:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install nfpm
        run: |
          curl -sSL -o nfpm.deb https://github.com/goreleaser/nfpm/releases/download/v2.41.2/nfpm_2.41.2_amd64.deb
          #file nfpm.deb  # Check if it's a valid .deb file
          ls -lh nfpm.deb
          sudo dpkg -i nfpm.deb || sudo apt-get install -f -y
          nfpm --version
  
      - name: Create Packages with nfpm
        run: |          
          mkdir -p dist
          nfpm package --config .github/nfpm.yaml --target dist --packager deb

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: packaged-files
          path: dist/*